# Generated by Django 5.0.6 on 2024-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_staff_status_user_is_staff_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo_path', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('price_band', models.CharField(blank=True, max_length=255, null=True)),
                ('open', models.CharField(blank=True, max_length=255, null=True)),
                ('close', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_size', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('ipo_price', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_price', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_gain', models.CharField(blank=True, max_length=255, null=True)),
                ('cmp', models.CharField(blank=True, max_length=255, null=True)),
                ('current_return', models.CharField(blank=True, max_length=255, null=True)),
                ('rhp', models.CharField(blank=True, max_length=255, null=True)),
                ('drhp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
